/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package generalServer;

import com.mysql.jdbc.Connection;
import java.net.MalformedURLException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sukalyan14
 */
public class HomeOptions extends javax.swing.JFrame {
    
    Connection databaseConnection;

    /**
     * Creates new form HomeOptions
     */
    public HomeOptions() {
        initComponents();
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
                    
            Connection con = (Connection)DriverManager.getConnection("jdbc:mysql://localhost:3306/peer01","root","database");
            //JOptionPane.showMessageDialog(this,"Please fill in your credentials");
            databaseConnection=con;
        }
        catch(SQLException e)
        {
            System.out.println("SQL Exception");
        }
        catch(ClassNotFoundException e)
        {
            System.out.println("Class not found");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        teacherRegistrationOption = new javax.swing.JButton();
        teacherDetailsOption = new javax.swing.JButton();
        teacherLoginOption = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        teacherRegistrationOption.setText(Util.messages.getString("headingTeacherRegistration"));
        teacherRegistrationOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherRegistrationOptionActionPerformed(evt);
            }
        });

        teacherDetailsOption.setText(Util.messages.getString("teacherDetails"));
        teacherDetailsOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherDetailsOptionActionPerformed(evt);
            }
        });

        teacherLoginOption.setText(Util.messages.getString("teacherLogin"));
        teacherLoginOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherLoginOptionActionPerformed(evt);
            }
        });

        exitButton.setText(Util.messages.getString("teacherLogin"));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherDetailsOption)
                    .addComponent(teacherLoginOption)
                    .addComponent(teacherRegistrationOption))
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {teacherDetailsOption, teacherLoginOption, teacherRegistrationOption});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(teacherRegistrationOption)
                .addGap(46, 46, 46)
                .addComponent(teacherDetailsOption)
                .addGap(43, 43, 43)
                .addComponent(teacherLoginOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>

    private void teacherRegistrationOptionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        
        TeacherLogin obj=new TeacherLogin(databaseConnection);
        obj.setVisible(true);
        this.setVisible(false);
    }

    private void teacherDetailsOptionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        TeacherDetails obj=new TeacherDetails(databaseConnection);
        obj.setVisible(true);
        this.setVisible(false);
    }

    private void teacherLoginOptionActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        LoginGeneral obj;
        try 
        {
            obj = new LoginGeneral(databaseConnection);
            obj.setVisible(true);
            this.setVisible(false);
        } 
        catch (MalformedURLException ex) 
        {
            Logger.getLogger(HomeOptions.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        System.exit(0);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new HomeOptions().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify
    private javax.swing.JButton exitButton;
    private javax.swing.JButton teacherDetailsOption;
    private javax.swing.JButton teacherLoginOption;
    private javax.swing.JButton teacherRegistrationOption;
    // End of variables declaration
}
