/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package generalServer;

import com.mysql.jdbc.Connection;
import java.net.MalformedURLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sukalyan14
 */
public class TeacherOptionGeneral extends javax.swing.JFrame {
    
    Connection databaseConnection;

    /**
     * Creates new form TeacherOption
     */
    public TeacherOptionGeneral(Connection db) {
        initComponents();
        databaseConnection=db;
       
    }

    public TeacherOptionGeneral() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewPerformance = new javax.swing.JButton();
        studentConfiguration = new javax.swing.JButton();
        uploadDocument = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();
        viewQuestion = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        
        viewPerformance.setText(Util.messages.getString("viewStudentPerformance"));
        viewPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPerformanceActionPerformed(evt);
            }
        });

        studentConfiguration.setText(Util.messages.getString("configureStudentDetails"));
        studentConfiguration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentConfigurationActionPerformed(evt);
            }
        });

        uploadDocument.setText(Util.messages.getString("uploadDocument"));

        quizButton.setText(Util.messages.getString("startQuiz"));
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });

        viewQuestion.setText(Util.messages.getString("viewQuestions"));
        viewQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewQuestionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(quizButton)
                    .addComponent(viewPerformance)
                    .addComponent(viewQuestion)
                    .addComponent(uploadDocument)
                    .addComponent(studentConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(282, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {quizButton, studentConfiguration, uploadDocument, viewPerformance, viewQuestion});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(studentConfiguration)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quizButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPerformance)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uploadDocument)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        logoutButton.setText(Util.messages.getString("logout"));
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try 
                {
                    logoutButtonActionPerformed(evt);
                } 
                catch (MalformedURLException ex) 
                {
                    Logger.getLogger(TeacherOptionGeneral.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(logoutButton)
                .addGap(0, 205, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) throws MalformedURLException {                                             
        // TODO add your handling code here:
        LoginGeneral obj=new LoginGeneral(databaseConnection); // going back to the login page
        obj.setVisible(true);
        this.setVisible(false);
        
        //Login.endLogin();
    }                                            

    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void studentConfigurationActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        // TODO add your handling code here:
        ConfigureStudentGeneral obj=new ConfigureStudentGeneral(databaseConnection);
        obj.setVisible(true);
        this.setVisible(false);
    }                                                    

    private void viewPerformanceActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        
        ViewPerformanceGeneral obj=new ViewPerformanceGeneral(databaseConnection);
        this.setVisible(false);
        obj.setVisible(true);
        
    }                                               

    private void viewQuestionActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handlig code here:
        
        ViewQuestionGeneral obj=new ViewQuestionGeneral(databaseConnection);
        this.setVisible(false);
        obj.setVisible(true);
    }                                            

    
    /**
     * @param args the command line arguments
     */
    
    static void endTeacherOption()
    {
        System.exit(0);         // exiting the Teacher option interface
       
    }
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherOptionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherOptionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherOptionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherOptionGeneral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TeacherOptionGeneral().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify                     
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutButton;
    private javax.swing.JButton quizButton;
    private javax.swing.JButton studentConfiguration;
    private javax.swing.JButton uploadDocument;
    private javax.swing.JButton viewPerformance;
    private javax.swing.JButton viewQuestion;
    // End of variables declaration                   
}
